[package]
name = "peroxide"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
console_error_panic_hook = "0.1.7"
wasm-bindgen = "0.2.100"
web-sys = { version = "0.3.77", features = ["console", "Window", "Document", "Element", "Event", "HtmlElement", "Node", "Window", "MouseEvent"] }
