use js_sys;
use wasm_bindgen::{JsCast, JsValue, prelude::*};
use web_sys::{Event, RtcConfiguration, RtcIceServer, RtcPeerConnection, RtcPeerConnectionIceEvent, RtcPeerConnectionState};

/// First step of protocol: Create a new `RtcPeerConnection` and set up the necessary event handlers.
/// 
/// We have two peers:
///
/// - The "host" (offerer) is the peer that initiates the connection by creating an offer.
/// - The "guest" (answerer) is the peer that receives the offer and creates an answer.
// 
/// Also see: https://datatracker.ietf.org/doc/html/rfc3264
///
/// # Arguments
///
/// - `on_handshake_generation` - A callback that is called when the ICE candidate gathering is complete and the SDP is ready to be sent to the other peer.
/// - `on_connection_status_change` - A callback that is called when the connection state of the peer connection changes.
pub fn create_peer_connection<F1, F2>(mut on_handshake_generation: F1, mut on_connection_status_change: F2) -> RtcPeerConnection
where
    F1: 'static + FnMut(String),
    F2: 'static + FnMut(&str),
{
    let ice_server = RtcIceServer::new();
    ice_server.set_urls(&js_sys::Array::of1(&JsValue::from_str("stun:stun.l.google.com:19302")));
    let configuration = RtcConfiguration::new();
    configuration.set_ice_servers(&js_sys::Array::of1(&ice_server));
    let pc = RtcPeerConnection::new_with_configuration(&configuration).unwrap();

    // the sdp offer/answer handshake is generated by both peers
    let onicecandidate_callback = Closure::wrap(Box::new(move |event: RtcPeerConnectionIceEvent| {
        if event.candidate().is_none() {
            let pc = event.current_target().unwrap().dyn_into::<RtcPeerConnection>().unwrap();
            if let Some(desc) = pc.local_description() {
                let json_str = js_sys::JSON::stringify(&desc).unwrap().as_string().unwrap();
                console_log!("generated sdp: {}", json_str);

                on_handshake_generation(json_str);
            }
        }
    }) as Box<dyn FnMut(RtcPeerConnectionIceEvent)>);
    pc.set_onicecandidate(Some(onicecandidate_callback.as_ref().unchecked_ref()));
    onicecandidate_callback.forget();

    // change in connection state
    let onconnectionstatechange_callback = Closure::wrap(Box::new(move |event: Event| {
        let pc = event.current_target().unwrap().dyn_into::<RtcPeerConnection>().unwrap();
        let state_str = match pc.connection_state() {
            RtcPeerConnectionState::New => "🟡 New",
            RtcPeerConnectionState::Connecting => "🟡 Connecting",
            RtcPeerConnectionState::Connected => "🟢 Connected",
            RtcPeerConnectionState::Disconnected => "🔴 Disconnected",
            RtcPeerConnectionState::Failed => "🔴 Failed",
            RtcPeerConnectionState::Closed => "🔴 Closed",
            _ => "🔴 Unknown error",
        };
        console_log!("connection status changed: {}", state_str);

        on_connection_status_change(state_str);
    }) as Box<dyn FnMut(Event)>);
    pc.set_onconnectionstatechange(Some(onconnectionstatechange_callback.as_ref().unchecked_ref()));
    onconnectionstatechange_callback.forget();

    pc
}
